### ISSUE TITLE
map OD1 workflowMetadata dsCreateDate to OD2 date_uploaded

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/hyrax-migrator#202]
@lsat12357 suggested that we could retrieve additional information during the datastream export step and then implement a new actor/service to map the info, in this case the workflowMetadata, from the bag.

findings:
- it looks like we can use `date_uploaded` in hyrax to preserve the original creation date on migrated items according to this note in the source: [app/models/concerns/hyrax/core_metadata.rb#L20-L24](https://github.com/samvera/hyrax/blob/625bcfdb7a70c752d19c9e8b9b43e8a9b945a515/app/models/concerns/hyrax/core_metadata.rb#L20-L24)
- hyrax uses `date_uploaded` as the date for analytics when building the stats for migrated items: [app/presenters/hyrax/stats_usage_presenter.rb#L24-L28](https://github.com/samvera/hyrax/blob/625bcfdb7a70c752d19c9e8b9b43e8a9b945a515/app/presenters/hyrax/stats_usage_presenter.rb#L24-L28)
[spec/presenters/hyrax/file_usage_spec.rb#L148](https://github.com/samvera/hyrax/blob/1477059ba7983bc3e1e3980d107d3ebc1b1f4af4/spec/presenters/hyrax/file_usage_spec.rb#L148)

Note from @wickr:
```
ptions:
  :profile: &165 !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    dsLabel: 
    dsVersionID: workflowMetadata.2
    dsCreateDate: 2014-10-03 23:29:55.132000000 Z
    dsState: A
    dsMIME: application/octet-stream
    dsFormatURI: 
    dsControlGroup: M
    dsSize: 39
    dsVersionable: true
    dsInfoType: 
    dsLocation: oregondigital:5m60qs614+workflowMetadata+workflowMetadata.2
    dsLocationType: INTERNAL_ID
    dsChecksumType: DISABLED
    dsChecksum: none
default_attributes:
  :controlGroup: M
  :dsState: A
  :versionable: true
  :asOfDateTime: 
```
