### ISSUE TITLE
escape special chars in profile yml

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/hyrax-migrator#205]
having a `"` character in the description breaks the YML parser when loading the original profile:
Example profile for `pid = df70dp55t`:
```
original_profile = YAML.load_file(File.join('/data/tmp/profiles/derivatives_info','df70dp55t_profile.yml'))
Psych::SyntaxError: (/data/tmp/profiles/derivatives_info/df70dp55t_profile.yml): did not find expected key while parsing a block mapping at line 25 column 3
from /usr/local/lib/ruby/2.5.0/psych.rb:402:in `parse'
```
It looks like YAML doesn't like `"` in the `description` field:
```
fields:
  title:
  - "Cruisers' Song"
  description:
  - "Sung by Forester's Chorus; recorded at KOAC Radio Station by J. M. Morris; Theme for Foresters in Action. (8" Vinyl Disc)"
  lcsubject:
  - "http://id.loc.gov/authorities/subjects/sh85125040"
```
```
Error : Unexpected characters near " Vinyl Disc)"".
Line : 28  - "Sung by Forester's Chorus; recorded at KOAC Radio Station by J. M. Morris; Theme for Foresters in Action. (8" Vinyl Disc)"
```
