### ISSUE TITLE
Crosswalk metadata service

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#27]
## Descriptive summary

Each registered model in the engine should point at the Hyrax "Work Type" that is part of the migration plan. Each of these "Work Types" need to have some configuration around how to crosswalk metadata from the original file (n-triples?) to the new work types properties. 

## Expected behavior

It could be a good first step to expect a configuration yaml in `config/migrator/` for each Work Type to describe the crosswalk. 

```
# config/hyrax-migrator/image.yml
---
crosswalk:
  - uri: http://purl.org/dc/terms/title
    property: subject
    multivalue: true
  - uri: http://purl.org/dc/terms/format
    property: format
    multivalue: true
```
