### ISSUE TITLE
Crosswalk special (linked data) metadata to a complex shape

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#77]
For OD2 we have a need to crosswalk some fields but provide a complex shape of data as the result of the crosswalk (so that the Hyrax ingest handles it properly).

One such attribute is `format` (there are others that have the same need for the following shape of data). 

OD2 `format` metadata should be added to the `Work.env[:attributes]` as `format_attributes: [{ 'id' => the_original_url_from_od1_string, '_destroy' => 0}]`.

Maybe we could replace `format` with a configuration to the crosswalk yaml files with a function that has access to the original metadata value but then spits out an arbitrary shape of data.. 

```yaml
...
  - property: format_attributes
    predicate: http://purl.org/dc/terms/format
    multiple: true
    function: attributes_data
...
```

And in the CrosswalkMetadataService we can introduce the method

```ruby
    def attributes_data(object)
      {'id' => object.to_s, '_destroy' => 0}
    end
```

@lsat12357 Thoughts?
